### PR TITLE
add geoweaver

### PR DESCRIPTION
**Pull request by ZihengSun**

### CODE REVIEW

**Comment by rafaelfsilva** [comment]
Thank you @ZihengSun! It would be great if you could add a `.wci.yml` file to your repository that would provide additional metadata to the website. You can find more details at the bottom of [this page](https://workflows.community/systems/contribute).

**Comment by ZihengSun** [comment]
Sure, working on it.

**Comment by rafaelfsilva** [comment]
All looks good (https://workflows.community/systems/geoweaver/). Thank you!

**Comment by ZihengSun** [comment]
@rafaelfsilva awesome! thanks a lot!

**Pull request merged**
