### PR TITLE
Add nnodes

### PR DESCRIPTION
**Pull request by icui**
https://github.com/icui/nnodes

### CODE REVIEW

**Comment by rafaelfsilva** [comment]
Thank you @icui, you request has been merged.
Could you please ensure the documentation for nnodes has all images working properly?

**Comment by icui** [comment]
> Thank you @icui, you request has been merged.
> Could you please ensure the documentation for nnodes has all images working properly?

The images are fixed now. Thanks for reminding.

**Comment by rafaelfsilva** [comment]
Thank you @icui!
Also, I noticed that the repository added to the yaml does not exist (or is not public): https://github.com/nnodes/nnodes

**Comment by icui** [comment]
The repo is icui/nnodes instead of nnodes/nnodes.

**Pull request merged**
