### PR TITLE
Add SmartSim to list of workflow systems

### PR DESCRIPTION
**Pull request by mellis13**
Hello,

I'd like to add [SmartSim](https://github.com/CrayLabs/SmartSim) to the list of workflow systems.  SmartSim is an open source workflow library actively developed by a Hewlett Packard Enterprise.  The ``.wci.yml`` has already been added to the SmartSim repository.  Thank you!

### CODE REVIEW

**Comment by rafaelfsilva** [comment]
Thank you @mellis13!

**Comment by mellis13** [comment]
@rafaelfsilva I'd be happy to write up a story about SmartSim for WCI.  Do I submit another PR adding a SmartSim story to the ``_stories`` directory?

**Comment by rafaelfsilva** [comment]
you can either do a PR or send it direct to me and I can incorporate it. Thanks!

**Comment by mellis13** [comment]
That sounds good -- I'll send you a draft of a SmartSim story in the next few week

**Pull request merged**
