### PR TITLE
Disabled Twitter widget, they broke their API again

### PR DESCRIPTION
**Pull request by stain**
see issue #65 -- the design may need to be adjusted if removing permanently.

### CODE REVIEW

**Comment by rafaelfsilva** [comment]
It looks like it is working again, but not sure for how long :/

**Comment by stain** [comment]
Still says "Nothing to see here - yet" for me -- perhaps users now need to be logged in (I deleted my X account last month)

**Comment by rafaelfsilva** [comment]
Thanks for letting me know. I will work on some updates for the website next week and will remove the widget.

**Comment by stain** [comment]
Also disabled for sub-pages.

**Pull request merged**
